//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hkrestaurant.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class acckh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acckh()
        {
            this.datban = new HashSet<datban>();
        }
    
        public int kh_ma { get; set; }
        public string kh_taikhoan { get; set; }
        public string kh_matkhau { get; set; }
        public string kh_tendaydu { get; set; }
        public string kh_sdt { get; set; }
        public string kh_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datban> datban { get; set; }
    }
}
