//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hkrestaurant.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HKRESTAURANT2Entities : DbContext
    {
        public HKRESTAURANT2Entities()
            : base("name=HKRESTAURANT2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acckh> acckh { get; set; }
        public virtual DbSet<adminn> adminn { get; set; }
        public virtual DbSet<chitietdatban> chitietdatban { get; set; }
        public virtual DbSet<datban> datban { get; set; }
        public virtual DbSet<loai> loai { get; set; }
        public virtual DbSet<monan> monan { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
