#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hkrestaurant.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HKRESTAURANT")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertacckh(acckh instance);
    partial void Updateacckh(acckh instance);
    partial void Deleteacckh(acckh instance);
    partial void Insertadminn(adminn instance);
    partial void Updateadminn(adminn instance);
    partial void Deleteadminn(adminn instance);
    partial void Insertchitietdatban(chitietdatban instance);
    partial void Updatechitietdatban(chitietdatban instance);
    partial void Deletechitietdatban(chitietdatban instance);
    partial void Insertdatban(datban instance);
    partial void Updatedatban(datban instance);
    partial void Deletedatban(datban instance);
    partial void Insertloai(loai instance);
    partial void Updateloai(loai instance);
    partial void Deleteloai(loai instance);
    partial void Insertmonan(monan instance);
    partial void Updatemonan(monan instance);
    partial void Deletemonan(monan instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HKRESTAURANT2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<acckh> acckhs
		{
			get
			{
				return this.GetTable<acckh>();
			}
		}
		
		public System.Data.Linq.Table<adminn> adminns
		{
			get
			{
				return this.GetTable<adminn>();
			}
		}
		
		public System.Data.Linq.Table<chitietdatban> chitietdatbans
		{
			get
			{
				return this.GetTable<chitietdatban>();
			}
		}
		
		public System.Data.Linq.Table<datban> datbans
		{
			get
			{
				return this.GetTable<datban>();
			}
		}
		
		public System.Data.Linq.Table<loai> loais
		{
			get
			{
				return this.GetTable<loai>();
			}
		}
		
		public System.Data.Linq.Table<monan> monans
		{
			get
			{
				return this.GetTable<monan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.acckh")]
	public partial class acckh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kh_ma;
		
		private string _kh_taikhoan;
		
		private string _kh_matkhau;
		
		private string _kh_tendaydu;
		
		private string _kh_sdt;
		
		private string _kh_email;
		
		private EntitySet<datban> _datbans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkh_maChanging(int value);
    partial void Onkh_maChanged();
    partial void Onkh_taikhoanChanging(string value);
    partial void Onkh_taikhoanChanged();
    partial void Onkh_matkhauChanging(string value);
    partial void Onkh_matkhauChanged();
    partial void Onkh_tendayduChanging(string value);
    partial void Onkh_tendayduChanged();
    partial void Onkh_sdtChanging(string value);
    partial void Onkh_sdtChanged();
    partial void Onkh_emailChanging(string value);
    partial void Onkh_emailChanged();
    #endregion
		
		public acckh()
		{
			this._datbans = new EntitySet<datban>(new Action<datban>(this.attach_datbans), new Action<datban>(this.detach_datbans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_ma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kh_ma
		{
			get
			{
				return this._kh_ma;
			}
			set
			{
				if ((this._kh_ma != value))
				{
					this.Onkh_maChanging(value);
					this.SendPropertyChanging();
					this._kh_ma = value;
					this.SendPropertyChanged("kh_ma");
					this.Onkh_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_taikhoan", DbType="VarChar(20)")]
		public string kh_taikhoan
		{
			get
			{
				return this._kh_taikhoan;
			}
			set
			{
				if ((this._kh_taikhoan != value))
				{
					this.Onkh_taikhoanChanging(value);
					this.SendPropertyChanging();
					this._kh_taikhoan = value;
					this.SendPropertyChanged("kh_taikhoan");
					this.Onkh_taikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_matkhau", DbType="VarChar(16)")]
		public string kh_matkhau
		{
			get
			{
				return this._kh_matkhau;
			}
			set
			{
				if ((this._kh_matkhau != value))
				{
					this.Onkh_matkhauChanging(value);
					this.SendPropertyChanging();
					this._kh_matkhau = value;
					this.SendPropertyChanged("kh_matkhau");
					this.Onkh_matkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_tendaydu", DbType="NVarChar(30)")]
		public string kh_tendaydu
		{
			get
			{
				return this._kh_tendaydu;
			}
			set
			{
				if ((this._kh_tendaydu != value))
				{
					this.Onkh_tendayduChanging(value);
					this.SendPropertyChanging();
					this._kh_tendaydu = value;
					this.SendPropertyChanged("kh_tendaydu");
					this.Onkh_tendayduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_sdt", DbType="VarChar(11)")]
		public string kh_sdt
		{
			get
			{
				return this._kh_sdt;
			}
			set
			{
				if ((this._kh_sdt != value))
				{
					this.Onkh_sdtChanging(value);
					this.SendPropertyChanging();
					this._kh_sdt = value;
					this.SendPropertyChanged("kh_sdt");
					this.Onkh_sdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_email", DbType="VarChar(30)")]
		public string kh_email
		{
			get
			{
				return this._kh_email;
			}
			set
			{
				if ((this._kh_email != value))
				{
					this.Onkh_emailChanging(value);
					this.SendPropertyChanging();
					this._kh_email = value;
					this.SendPropertyChanged("kh_email");
					this.Onkh_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="acckh_datban", Storage="_datbans", ThisKey="kh_ma", OtherKey="kh_ma")]
		public EntitySet<datban> datbans
		{
			get
			{
				return this._datbans;
			}
			set
			{
				this._datbans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_datbans(datban entity)
		{
			this.SendPropertyChanging();
			entity.acckh = this;
		}
		
		private void detach_datbans(datban entity)
		{
			this.SendPropertyChanging();
			entity.acckh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.adminn")]
	public partial class adminn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _admin_ma;
		
		private string _admin_taikhoan;
		
		private string _admin_matkhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_maChanging(int value);
    partial void Onadmin_maChanged();
    partial void Onadmin_taikhoanChanging(string value);
    partial void Onadmin_taikhoanChanged();
    partial void Onadmin_matkhauChanging(string value);
    partial void Onadmin_matkhauChanged();
    #endregion
		
		public adminn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_ma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int admin_ma
		{
			get
			{
				return this._admin_ma;
			}
			set
			{
				if ((this._admin_ma != value))
				{
					this.Onadmin_maChanging(value);
					this.SendPropertyChanging();
					this._admin_ma = value;
					this.SendPropertyChanged("admin_ma");
					this.Onadmin_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_taikhoan", DbType="NVarChar(20)")]
		public string admin_taikhoan
		{
			get
			{
				return this._admin_taikhoan;
			}
			set
			{
				if ((this._admin_taikhoan != value))
				{
					this.Onadmin_taikhoanChanging(value);
					this.SendPropertyChanging();
					this._admin_taikhoan = value;
					this.SendPropertyChanged("admin_taikhoan");
					this.Onadmin_taikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_matkhau", DbType="VarChar(16)")]
		public string admin_matkhau
		{
			get
			{
				return this._admin_matkhau;
			}
			set
			{
				if ((this._admin_matkhau != value))
				{
					this.Onadmin_matkhauChanging(value);
					this.SendPropertyChanging();
					this._admin_matkhau = value;
					this.SendPropertyChanged("admin_matkhau");
					this.Onadmin_matkhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietdatban")]
	public partial class chitietdatban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kh_ma;
		
		private System.Nullable<int> _songuoi;
		
		private string _ctdb_tenmon;
		
		private string _ctdb_thoigian;
		
		private int _ctdb_ma;
		
		private int _datban_ma;
		
		private EntityRef<datban> _datban;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkh_maChanging(int value);
    partial void Onkh_maChanged();
    partial void OnsonguoiChanging(System.Nullable<int> value);
    partial void OnsonguoiChanged();
    partial void Onctdb_tenmonChanging(string value);
    partial void Onctdb_tenmonChanged();
    partial void Onctdb_thoigianChanging(string value);
    partial void Onctdb_thoigianChanged();
    partial void Onctdb_maChanging(int value);
    partial void Onctdb_maChanged();
    partial void Ondatban_maChanging(int value);
    partial void Ondatban_maChanged();
    #endregion
		
		public chitietdatban()
		{
			this._datban = default(EntityRef<datban>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_ma", DbType="Int NOT NULL")]
		public int kh_ma
		{
			get
			{
				return this._kh_ma;
			}
			set
			{
				if ((this._kh_ma != value))
				{
					this.Onkh_maChanging(value);
					this.SendPropertyChanging();
					this._kh_ma = value;
					this.SendPropertyChanged("kh_ma");
					this.Onkh_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songuoi", DbType="Int")]
		public System.Nullable<int> songuoi
		{
			get
			{
				return this._songuoi;
			}
			set
			{
				if ((this._songuoi != value))
				{
					this.OnsonguoiChanging(value);
					this.SendPropertyChanging();
					this._songuoi = value;
					this.SendPropertyChanged("songuoi");
					this.OnsonguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctdb_tenmon", DbType="NVarChar(30)")]
		public string ctdb_tenmon
		{
			get
			{
				return this._ctdb_tenmon;
			}
			set
			{
				if ((this._ctdb_tenmon != value))
				{
					this.Onctdb_tenmonChanging(value);
					this.SendPropertyChanging();
					this._ctdb_tenmon = value;
					this.SendPropertyChanged("ctdb_tenmon");
					this.Onctdb_tenmonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctdb_thoigian", DbType="NVarChar(30)")]
		public string ctdb_thoigian
		{
			get
			{
				return this._ctdb_thoigian;
			}
			set
			{
				if ((this._ctdb_thoigian != value))
				{
					this.Onctdb_thoigianChanging(value);
					this.SendPropertyChanging();
					this._ctdb_thoigian = value;
					this.SendPropertyChanged("ctdb_thoigian");
					this.Onctdb_thoigianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctdb_ma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ctdb_ma
		{
			get
			{
				return this._ctdb_ma;
			}
			set
			{
				if ((this._ctdb_ma != value))
				{
					if (this._datban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onctdb_maChanging(value);
					this.SendPropertyChanging();
					this._ctdb_ma = value;
					this.SendPropertyChanged("ctdb_ma");
					this.Onctdb_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datban_ma", DbType="Int NOT NULL")]
		public int datban_ma
		{
			get
			{
				return this._datban_ma;
			}
			set
			{
				if ((this._datban_ma != value))
				{
					this.Ondatban_maChanging(value);
					this.SendPropertyChanging();
					this._datban_ma = value;
					this.SendPropertyChanged("datban_ma");
					this.Ondatban_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="datban_chitietdatban", Storage="_datban", ThisKey="ctdb_ma", OtherKey="datban_ma", IsForeignKey=true)]
		public datban datban
		{
			get
			{
				return this._datban.Entity;
			}
			set
			{
				datban previousValue = this._datban.Entity;
				if (((previousValue != value) 
							|| (this._datban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._datban.Entity = null;
						previousValue.chitietdatban = null;
					}
					this._datban.Entity = value;
					if ((value != null))
					{
						value.chitietdatban = this;
						this._ctdb_ma = value.datban_ma;
					}
					else
					{
						this._ctdb_ma = default(int);
					}
					this.SendPropertyChanged("datban");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.datban")]
	public partial class datban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _datban_ma;
		
		private System.Nullable<int> _kh_ma;
		
		private System.Nullable<System.DateTime> _ngaythang;
		
		private string _loaiban;
		
		private EntityRef<chitietdatban> _chitietdatban;
		
		private EntityRef<acckh> _acckh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondatban_maChanging(int value);
    partial void Ondatban_maChanged();
    partial void Onkh_maChanging(System.Nullable<int> value);
    partial void Onkh_maChanged();
    partial void OnngaythangChanging(System.Nullable<System.DateTime> value);
    partial void OnngaythangChanged();
    partial void OnloaibanChanging(string value);
    partial void OnloaibanChanged();
    #endregion
		
		public datban()
		{
			this._chitietdatban = default(EntityRef<chitietdatban>);
			this._acckh = default(EntityRef<acckh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datban_ma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int datban_ma
		{
			get
			{
				return this._datban_ma;
			}
			set
			{
				if ((this._datban_ma != value))
				{
					this.Ondatban_maChanging(value);
					this.SendPropertyChanging();
					this._datban_ma = value;
					this.SendPropertyChanged("datban_ma");
					this.Ondatban_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kh_ma", DbType="Int")]
		public System.Nullable<int> kh_ma
		{
			get
			{
				return this._kh_ma;
			}
			set
			{
				if ((this._kh_ma != value))
				{
					if (this._acckh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkh_maChanging(value);
					this.SendPropertyChanging();
					this._kh_ma = value;
					this.SendPropertyChanged("kh_ma");
					this.Onkh_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythang
		{
			get
			{
				return this._ngaythang;
			}
			set
			{
				if ((this._ngaythang != value))
				{
					this.OnngaythangChanging(value);
					this.SendPropertyChanging();
					this._ngaythang = value;
					this.SendPropertyChanged("ngaythang");
					this.OnngaythangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiban", DbType="VarChar(10)")]
		public string loaiban
		{
			get
			{
				return this._loaiban;
			}
			set
			{
				if ((this._loaiban != value))
				{
					this.OnloaibanChanging(value);
					this.SendPropertyChanging();
					this._loaiban = value;
					this.SendPropertyChanged("loaiban");
					this.OnloaibanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="datban_chitietdatban", Storage="_chitietdatban", ThisKey="datban_ma", OtherKey="ctdb_ma", IsUnique=true, IsForeignKey=false)]
		public chitietdatban chitietdatban
		{
			get
			{
				return this._chitietdatban.Entity;
			}
			set
			{
				chitietdatban previousValue = this._chitietdatban.Entity;
				if (((previousValue != value) 
							|| (this._chitietdatban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chitietdatban.Entity = null;
						previousValue.datban = null;
					}
					this._chitietdatban.Entity = value;
					if ((value != null))
					{
						value.datban = this;
					}
					this.SendPropertyChanged("chitietdatban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="acckh_datban", Storage="_acckh", ThisKey="kh_ma", OtherKey="kh_ma", IsForeignKey=true)]
		public acckh acckh
		{
			get
			{
				return this._acckh.Entity;
			}
			set
			{
				acckh previousValue = this._acckh.Entity;
				if (((previousValue != value) 
							|| (this._acckh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._acckh.Entity = null;
						previousValue.datbans.Remove(this);
					}
					this._acckh.Entity = value;
					if ((value != null))
					{
						value.datbans.Add(this);
						this._kh_ma = value.kh_ma;
					}
					else
					{
						this._kh_ma = default(Nullable<int>);
					}
					this.SendPropertyChanged("acckh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loai")]
	public partial class loai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loai_ma;
		
		private string _loai_ten;
		
		private EntitySet<monan> _monans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onloai_maChanging(int value);
    partial void Onloai_maChanged();
    partial void Onloai_tenChanging(string value);
    partial void Onloai_tenChanged();
    #endregion
		
		public loai()
		{
			this._monans = new EntitySet<monan>(new Action<monan>(this.attach_monans), new Action<monan>(this.detach_monans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_ma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int loai_ma
		{
			get
			{
				return this._loai_ma;
			}
			set
			{
				if ((this._loai_ma != value))
				{
					this.Onloai_maChanging(value);
					this.SendPropertyChanging();
					this._loai_ma = value;
					this.SendPropertyChanged("loai_ma");
					this.Onloai_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_ten", DbType="NVarChar(30)")]
		public string loai_ten
		{
			get
			{
				return this._loai_ten;
			}
			set
			{
				if ((this._loai_ten != value))
				{
					this.Onloai_tenChanging(value);
					this.SendPropertyChanging();
					this._loai_ten = value;
					this.SendPropertyChanged("loai_ten");
					this.Onloai_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loai_monan", Storage="_monans", ThisKey="loai_ma", OtherKey="loai_ma")]
		public EntitySet<monan> monans
		{
			get
			{
				return this._monans;
			}
			set
			{
				this._monans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_monans(monan entity)
		{
			this.SendPropertyChanging();
			entity.loai = this;
		}
		
		private void detach_monans(monan entity)
		{
			this.SendPropertyChanging();
			entity.loai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.monan")]
	public partial class monan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _monan_ma;
		
		private System.Nullable<int> _loai_ma;
		
		private string _monan_ten;
		
		private string _monan_hinh;
		
		private double _monan_gia;
		
		private string _monan_mota;
		
		private EntityRef<loai> _loai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmonan_maChanging(int value);
    partial void Onmonan_maChanged();
    partial void Onloai_maChanging(System.Nullable<int> value);
    partial void Onloai_maChanged();
    partial void Onmonan_tenChanging(string value);
    partial void Onmonan_tenChanged();
    partial void Onmonan_hinhChanging(string value);
    partial void Onmonan_hinhChanged();
    partial void Onmonan_giaChanging(double value);
    partial void Onmonan_giaChanged();
    partial void Onmonan_motaChanging(string value);
    partial void Onmonan_motaChanged();
    #endregion
		
		public monan()
		{
			this._loai = default(EntityRef<loai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monan_ma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int monan_ma
		{
			get
			{
				return this._monan_ma;
			}
			set
			{
				if ((this._monan_ma != value))
				{
					this.Onmonan_maChanging(value);
					this.SendPropertyChanging();
					this._monan_ma = value;
					this.SendPropertyChanged("monan_ma");
					this.Onmonan_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_ma", DbType="Int")]
		public System.Nullable<int> loai_ma
		{
			get
			{
				return this._loai_ma;
			}
			set
			{
				if ((this._loai_ma != value))
				{
					if (this._loai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onloai_maChanging(value);
					this.SendPropertyChanging();
					this._loai_ma = value;
					this.SendPropertyChanged("loai_ma");
					this.Onloai_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monan_ten", DbType="VarChar(30)")]
		public string monan_ten
		{
			get
			{
				return this._monan_ten;
			}
			set
			{
				if ((this._monan_ten != value))
				{
					this.Onmonan_tenChanging(value);
					this.SendPropertyChanging();
					this._monan_ten = value;
					this.SendPropertyChanged("monan_ten");
					this.Onmonan_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monan_hinh", DbType="VarChar(30)")]
		public string monan_hinh
		{
			get
			{
				return this._monan_hinh;
			}
			set
			{
				if ((this._monan_hinh != value))
				{
					this.Onmonan_hinhChanging(value);
					this.SendPropertyChanging();
					this._monan_hinh = value;
					this.SendPropertyChanged("monan_hinh");
					this.Onmonan_hinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monan_gia", DbType="Float NOT NULL")]
		public double monan_gia
		{
			get
			{
				return this._monan_gia;
			}
			set
			{
				if ((this._monan_gia != value))
				{
					this.Onmonan_giaChanging(value);
					this.SendPropertyChanging();
					this._monan_gia = value;
					this.SendPropertyChanged("monan_gia");
					this.Onmonan_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monan_mota", DbType="NVarChar(255)")]
		public string monan_mota
		{
			get
			{
				return this._monan_mota;
			}
			set
			{
				if ((this._monan_mota != value))
				{
					this.Onmonan_motaChanging(value);
					this.SendPropertyChanging();
					this._monan_mota = value;
					this.SendPropertyChanged("monan_mota");
					this.Onmonan_motaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loai_monan", Storage="_loai", ThisKey="loai_ma", OtherKey="loai_ma", IsForeignKey=true)]
		public loai loai
		{
			get
			{
				return this._loai.Entity;
			}
			set
			{
				loai previousValue = this._loai.Entity;
				if (((previousValue != value) 
							|| (this._loai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loai.Entity = null;
						previousValue.monans.Remove(this);
					}
					this._loai.Entity = value;
					if ((value != null))
					{
						value.monans.Add(this);
						this._loai_ma = value.loai_ma;
					}
					else
					{
						this._loai_ma = default(Nullable<int>);
					}
					this.SendPropertyChanged("loai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
